namespace: /revolute
BODY body:
  color: random
  inertial offset:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: 0.0, y: 0.0, z: 0.0}
  location:
    orientation: {p: -0.0, r: 0.0, y: 0.0}
    position: {x: 0.0, y: 0.0, z: 1.1304}
  mass: 0
  mesh: body.STL
  name: body
  publish joint positions: True
  publish children names: True
  scale: 1.57
BODY left_foot:
  color: random
  inertial offset:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: 0.0, y: -0.042, z: 0.0}
  location:
    orientation: {p: 1.571, r: -0.0, y: 0.0}
    position: {x: 0.15072000000000002, y: 0.0, z: 0.06123}
  mass: 0.8905
  mesh: left_foot.STL
  name: left_foot
  scale: 1.57
BODY left_shank:
  color: random
  inertial offset:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: 0.097675038, y: 0.0, z: -0.0}
  location:
    orientation: {p: 1.571, r: 0.0, y: 0.0}
    position: {x: 0.15072000000000002, y: -0.0, z: 0.44744999999999996}
  mass: 2.8145
  mesh: left_shank.STL
  name: left_shank
  scale: 1.57
BODY left_thigh:
  color: random
  inertial offset:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: 0.09327762499999999, y: -0.002, z: 0.0}
  location:
    orientation: {p: 1.571, r: -0.0, y: 0.0}
    position: {x: 0.15072000000000002, y: 0.0, z: 0.8321000000000001}
  mass: 9.204
  mesh: left_thigh.STL
  name: left_thigh
  scale: 1.57
BODY right_foot:
  color: random
  inertial offset:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: 0.0, y: -0.042, z: 0.0}
  location:
    orientation: {p: 1.571, r: -0.0, y: 0.0}
    position: {x: -0.15072000000000002, y: 0.0, z: 0.06123}
  mass: 0.8905
  mesh: right_foot.STL
  name: right_foot
  scale: 1.57
BODY right_shank:
  color: random
  inertial offset:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: 0.097675038, y: 0.0, z: -0.0}
  location:
    orientation: {p: 1.571, r: 0.0, y: 0.0}
    position: {x: -0.15072000000000002, y: -0.0, z: 0.44744999999999996}
  mass: 2.8145
  mesh: right_shank.STL
  name: right_shank
  scale: 1.57
BODY right_thigh:
  color: random
  inertial offset:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: 0.09327762499999999, y: -0.002, z: 0.0}
  location:
    orientation: {p: 1.571, r: 0.0, y: 0.0}
    position: {x: -0.15072000000000002, y: 0.0, z: 0.8321000000000001}
  mass: 9.204
  mesh: right_thigh.STL
  name: right_thigh
  scale: 1.57
JOINT body-left_thigh:
  child: BODY left_thigh
  child axis: {x: 0.0, y: 0.0, z: 1.0}
  child pivot: {x: 0.0, y: 0.0, z: 0.0}
  enable motor: 1
  joint limits: {high: 0.5235987755982988, low: -1.9198621771937625}
  max motor impulse: 0.05
  damping: 80.0
  name: left_hip
  parent: BODY body
  parent axis: {x: 1.0, y: 0.0, z: 0.0}
  parent pivot: {x: 0.15072000000000002, y: 0.0, z: -0.2983}
  type: revolute
JOINT body-right_thigh:
  child: BODY right_thigh
  child axis: {x: 0.0, y: 0.0, z: 1.0}
  child pivot: {x: 0.0, y: 0.0, z: 0.0}
  enable motor: 1
  joint limits: {high: 3.14, low: -3.14 }
  max motor impulse: 0.05
  name: right_hip
  parent: BODY body
  parent axis: {x: 1.0, y: -0.0, z: 0.0}
  parent pivot: {x: -0.15072000000000002, y: 0.0, z: -0.2983}
  type: revolute
JOINT left_shank-left_foot:
  child: BODY left_foot
  child axis: {x: 0.0, y: 0.0, z: 1.0}
  child pivot: {x: 0.0, y: 0.0, z: 0.0}
  enable motor: 1
  joint limits: {high: 0.8726646259971648, low: -0.3490658503988659}
  max motor impulse: 0.05
  damping: 80.0
  name: left_ankle
  parent: BODY left_shank
  parent axis: {x: -0.0, y: 0.0, z: 1.0}
  parent pivot: {x: 0.38622, y: 0.0, z: -0.0}
  type: revolute
JOINT left_thigh-left_shank:
  child: BODY left_shank
  child axis: {x: 0.0, y: 0.0, z: 1.0}
  child pivot: {x: 0.0, y: 0.0, z: 0.0}
  enable motor: 1
  joint limits: {high: 2.0943951023931953, low: 0}
  max motor impulse: 0.05
  damping: 0
  name: left_knee
  parent: BODY left_thigh
  parent axis: {x: 0.0, y: -0.0, z: 1.0}
  parent pivot: {x: 0.38465, y: -0.0, z: -0.0}
  type: revolute
JOINT right_thigh-right_shank:
  child: BODY right_shank
  child axis: {x: 0.0, y: 0.0, z: 1.0}
  child pivot: {x: 0.0, y: 0.0, z: 0.0}
  enable motor: 1
  joint limits: {high: 2.0943951023931953, low: 0}
  max motor impulse: 0.000005
  name: right_knee
  parent: BODY right_thigh
  parent axis: {x: 0.0, y: -0.0, z: 1.0}
  parent pivot: {x: 0.38465, y: -0.0, z: -0.0}
  type: revolute
JOINT right_shank-right_foot:
  child: BODY right_foot
  child axis: {x: 0.0, y: 0.0, z: 1.0}
  child pivot: {x: 0.0, y: 0.0, z: 0.0}
  enable motor: 1
  joint limits: {high: 0.8726646259971648, low: -0.3490658503988659}
  max motor impulse: 0.000005
  name: right_ankle
  parent: BODY right_shank
  parent axis: {x: -0.0, y: 0.0, z: 1.0}
  parent pivot: {x: 0.38622, y: 0.0, z: -0.0}
  type: revolute
bodies: [BODY body, BODY left_foot, BODY left_shank, BODY left_thigh,
  BODY right_foot, BODY right_shank, BODY right_thigh]
high resolution path: ../meshes/high_res/
ignore inter-collision: 'True'
joints: [JOINT body-left_thigh,  JOINT left_thigh-left_shank,JOINT left_shank-left_foot,
  JOINT body-right_thigh, JOINT right_thigh-right_shank,  JOINT right_shank-right_foot]
low resolution path: ../meshes/low_res/
